parameters:
  - name: blackDuckApiToken
    type: string
    default: ""

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: azure-flutter-tasks
    type: github
    name: dtran272/azure-flutter-tasks
    endpoint: "DK's GitHub"

steps:
  - checkout: azure-flutter-tasks
  
  # - script: |
  #     sudo snap install flutter --classic
  #   displayName: 'Install Flutter'

  # - script: |
  #     flutter pub get
  #     flutter build apk
  #   displayName: 'Build Android'

  - task: Bash@3
    displayName: BlackDuck Detect Scan Step
    inputs:
      targetType: "inline"
      script: |
        bash <(curl -s https://detect.synopsys.com/detect9.sh) \
        --blackduck.api.token=${{ parameters.blackDuckApiToken }} \
        --blackduck.url='https://genetec.blackducksoftware.com/' \
        --detect.blackduck.scan.mode=RAPID \
        --detect.code.location.name="AutoVu.Mobile-$(Build.Repository.Name)" \
        --detect.detector.search.continue=true \
        --detect.detector.search.depth=5 \
        --detect.project.group.name="AutoVu.Mobile" \
        --detect.project.name="AutoVu.Mobile-azure-flutter-tasks" \
        --detect.project.version.distribution=SAAS \
        --detect.project.version.name=1 \
        --detect.project.version.notes="$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)" \
        --detect.project.version.update=true \
        --detect.source.path=$(Build.Repository.LocalPath)/tasks \
        --detect.output.path=$(Build.ArtifactStagingDirectory)/blackduck \
        --detect.wait.for.results=true \
        --detect.cleanup=false \
        --logging.level.detect=INFO