trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: azure-flutter-tasks
    type: github
    name: dtran272/azure-flutter-tasks
    endpoint: "DK's GitHub"

steps:
  - checkout: azure-flutter-tasks
  - task: SynopsysDetectTask@9
    displayName: 'BlackDuck Detect Scan'
    inputs:
      BlackDuckService: 'BlackDuck'
      DetectVersion: 'latest'
      DetectFolder: 'c:\BlackDuck'
      DetectArguments: |
        --detect.project.name=azure-flutter-tasks
        --detect.detector.search.continue=true
        --detect.detector.search.depth=$(BlackDuck.SearchDepth) 
        --detect.bom.aggregate.name=BDIOAggregateName
        --detect.project.version.notes="$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
        --detect.project.version.update=true